language: node_js
services:
- docker
cache:
  directories:
  - ~/.nvm
  - node_modules
env:
  global:
  - RELEASE_BRANCH="master"
  - DOCKER_HUB_ACCOUNT="frontband"
  - MAIN_BRANCHES="master develop"
node_js:
- 7.5.0
install:
- yarn install --no-progress --frozen-lockfile
before_install:
- chmod -R +x bin
script:
- yarn test
- yarn lint
- ./bin/version-increment.sh
- ./bin/build.sh
- ./bin/start.sh
- sleep 5
- docker ps
- RUNNING_CONTAINERS=`docker ps | wc -l`; if [ "${RUNNING_CONTAINERS//[[:space:]]/}"
  == "1" ]; then echo "[E] Container is not started\!"; docker logs react-boilerplate --details
  --since 5h; exit 1; fi;
- sleep 5
after_success:
- ./bin/ci/push.sh
